export type LabCategory = 'all' | 'physics' | 'complex' | 'optics' | 'retro';

export interface LabItem {
    slug: string;
    title: string;
    shortTitle: string;
    description: string;
    action: string;
    category: 'physics' | 'complex' | 'optics' | 'retro';
    categoryLabel: string;
    tags: string[];
    accentText: string;
    accentBorder: string;
    accentBg: string;
    iconName: string;
}

export const LAB_CATEGORIES: { id: LabCategory; label: string; count?: number }[] = [
    { id: 'all', label: 'Todos os Experimentos' },
    { id: 'physics', label: 'Física & Gravidade' },
    { id: 'complex', label: 'Sistemas Complexos & Vida' },
    { id: 'optics', label: 'Óptica, Ondas & Caos' },
    { id: 'retro', label: 'Gráficos, Retrô & Áudio' },
];

export const LAB_ITEMS: LabItem[] = [
    {
        slug: 'keyboard',
        title: 'RGB Keyboard Engine',
        shortTitle: 'RGB Keyboard',
        description: 'Teclado interativo 3D com síntese sonora de áudio procedural, iluminação reativa e resposta ao toque.',
        action: 'Testar Teclado',
        category: 'retro',
        categoryLabel: 'Gráficos, Retrô & Áudio',
        tags: ['Web Audio', 'CSS 3D', 'Procedural'],
        accentText: 'text-cyan-400',
        accentBorder: 'hover:border-cyan-500/50',
        accentBg: 'bg-cyan-500/10',
        iconName: 'Keyboard',
    },
    {
        slug: 'orbit',
        title: 'Orbital Field Simulator',
        shortTitle: 'Orbital Field',
        description: 'Simulador de partículas interativo com campos gravitacionais, forças eletromagnéticas e atratores orbitais.',
        action: 'Iniciar Simulação',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['Canvas 2D', 'Cinemática', 'Partículas'],
        accentText: 'text-blue-400',
        accentBorder: 'hover:border-blue-500/50',
        accentBg: 'bg-blue-500/10',
        iconName: 'Atom',
    },
    {
        slug: 'blackhole',
        title: 'Interstellar Gargantua',
        shortTitle: 'Gargantua BH',
        description: 'Simulação física relativística de um buraco negro supermassivo utilizando Raymarching e WebGL 2.0.',
        action: 'Entrar no Horizonte',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['WebGL 2.0', 'Raymarching', 'Relatividade'],
        accentText: 'text-orange-400',
        accentBorder: 'hover:border-orange-500/50',
        accentBg: 'bg-orange-500/10',
        iconName: 'CircleDashed',
    },
    {
        slug: 'matrix',
        title: 'Matrix Digital Rain',
        shortTitle: 'Matrix Rain',
        description: 'Chuva de códigos procedurais com efeito de profundidade 3D (Parallax), glyphs katakana e renderização ultra-otimizada.',
        action: 'Hack the Mainframe',
        category: 'retro',
        categoryLabel: 'Gráficos, Retrô & Áudio',
        tags: ['Canvas 2D', 'Parallax 3D', 'Retrô'],
        accentText: 'text-green-400',
        accentBorder: 'hover:border-green-500/50',
        accentBg: 'bg-green-500/10',
        iconName: 'Terminal',
    },
    {
        slug: 'explosion',
        title: 'Particle Text Physics',
        shortTitle: 'Particle Physics',
        description: 'Manipulação de pixels via Canvas API com física de repulsão elástica e reconstrução vetorial em tempo real.',
        action: 'Dispersar Texto',
        category: 'retro',
        categoryLabel: 'Gráficos, Retrô & Áudio',
        tags: ['Canvas 2D', 'Pixel Buffer', 'Física 2D'],
        accentText: 'text-yellow-400',
        accentBorder: 'hover:border-yellow-500/50',
        accentBg: 'bg-yellow-500/10',
        iconName: 'Zap',
    },
    {
        slug: 'vaporwave',
        title: 'Retro Vaporwave',
        shortTitle: 'Vaporwave',
        description: 'Cena procedural Outrun dos anos 80 renderizada puramente em Canvas 2D com horizonte infinito e sol vetorial.',
        action: 'Entrar no Grid',
        category: 'retro',
        categoryLabel: 'Gráficos, Retrô & Áudio',
        tags: ['Canvas 2D', 'Wireframe', 'Synthwave'],
        accentText: 'text-fuchsia-400',
        accentBorder: 'hover:border-fuchsia-500/50',
        accentBg: 'bg-fuchsia-500/10',
        iconName: 'Mountain',
    },
    {
        slug: 'neon',
        title: 'Neon Sign Generator',
        shortTitle: 'Neon Generator',
        description: 'Gerador de letreiros neon realista com efeitos de luminescência multifásica e simulação de descarga elétrica de gás.',
        action: 'Customizar Placa',
        category: 'retro',
        categoryLabel: 'Gráficos, Retrô & Áudio',
        tags: ['CSS Glow', 'Luminescência', 'SVG Filter'],
        accentText: 'text-pink-400',
        accentBorder: 'hover:border-pink-500/50',
        accentBg: 'bg-pink-500/10',
        iconName: 'Sparkles',
    },
    {
        slug: 'fluid',
        title: 'Fluid Simulation',
        shortTitle: 'GPU Fluid',
        description: 'Simulação de fluidos em tempo real utilizando GPU com Navier-Stokes, pressão e vorticidade interativa.',
        action: 'Perturbar Fluido',
        category: 'retro',
        categoryLabel: 'Gráficos, Retrô & Áudio',
        tags: ['WebGL 2.0', 'Navier-Stokes', 'Shader FBO'],
        accentText: 'text-teal-400',
        accentBorder: 'hover:border-teal-500/50',
        accentBg: 'bg-teal-500/10',
        iconName: 'Waves',
    },
    {
        slug: 'chladni',
        title: 'Chladni Resonance Patterns',
        shortTitle: 'Chladni Resonator',
        description: 'Simulação acústica de placas ressonantes em Canvas 2D com nós harmônicos e síntese de frequências em Web Audio.',
        action: 'Excitar a Placa',
        category: 'optics',
        categoryLabel: 'Óptica, Ondas & Caos',
        tags: ['Web Audio', 'Canvas 2D', 'Acústica Modal'],
        accentText: 'text-amber-400',
        accentBorder: 'hover:border-amber-500/50',
        accentBg: 'bg-amber-500/10',
        iconName: 'Disc',
    },
    {
        slug: 'mandelbulb',
        title: 'Raymarched 3D Mandelbulb',
        shortTitle: 'Mandelbulb 3D',
        description: 'Raymarching volumétrico em WebGL 2.0 de fractal hiperdimensional com órbita esférica e estimativa de distância.',
        action: 'Explorar Fractal',
        category: 'optics',
        categoryLabel: 'Óptica, Ondas & Caos',
        tags: ['WebGL 2.0', 'SDF Raymarching', 'Fractal 3D'],
        accentText: 'text-violet-400',
        accentBorder: 'hover:border-violet-500/50',
        accentBg: 'bg-violet-500/10',
        iconName: 'Boxes',
    },
    {
        slug: 'cloth',
        title: 'Verlet Cloth Simulation',
        shortTitle: 'Verlet Cloth',
        description: 'Física têxtil interativa em Canvas 2D com integração Verlet, relaxamento de restrições, arrasto elástico e corte de malha.',
        action: 'Manipular Tecido',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['Canvas 2D', 'Integração Verlet', 'Mecânica Têxtil'],
        accentText: 'text-rose-400',
        accentBorder: 'hover:border-rose-500/50',
        accentBg: 'bg-rose-500/10',
        iconName: 'Scissors',
    },
    {
        slug: 'jelly',
        title: 'Soft-Body Jelly Physics',
        shortTitle: 'Soft Jelly',
        description: 'Mecânica de corpos deformáveis com conservação de volume, pressão hidrostática, deformação elástica e resposta tátil.',
        action: 'Apertar Gelatina',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['Canvas 2D', 'Soft-Body', 'Pressão Hidrostática'],
        accentText: 'text-emerald-400',
        accentBorder: 'hover:border-emerald-500/50',
        accentBg: 'bg-emerald-500/10',
        iconName: 'Droplets',
    },
    {
        slug: 'pendulum',
        title: 'Chaotic Double Pendulum',
        shortTitle: 'Chaos Pendulum',
        description: 'Dinâmica caótica hamiltoniana integrada com Runge-Kutta de 4ª ordem (RK4), divergência de Lyapunov e rastros fosforescentes.',
        action: 'Liberar Pêndulo',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['Canvas 2D', 'Física RK4', 'Caos Hamiltoniano'],
        accentText: 'text-sky-400',
        accentBorder: 'hover:border-sky-500/50',
        accentBg: 'bg-sky-500/10',
        iconName: 'Infinity',
    },
    {
        slug: 'morphogenesis',
        title: 'Reaction-Diffusion Morphogenesis',
        shortTitle: 'Morphogenesis',
        description: 'Equações de Alan Turing e sistema Gray-Scott para geração de peles orgânicas, mitose celular, corais e labirintos químicos.',
        action: 'Semear Reação',
        category: 'complex',
        categoryLabel: 'Sistemas Complexos & Vida',
        tags: ['Canvas 2D', 'Gray-Scott', 'Biologia Teórica'],
        accentText: 'text-purple-400',
        accentBorder: 'hover:border-purple-500/50',
        accentBg: 'bg-purple-500/10',
        iconName: 'Fingerprint',
    },
    {
        slug: 'sandpile',
        title: 'Abelian Sandpile & Avalanches',
        shortTitle: 'Critical Sandpile',
        description: 'Auto-organização crítica e física granular em tempo real: cascatas de avalanches em leis de potência e fractais abelianos.',
        action: 'Despejar Areia',
        category: 'complex',
        categoryLabel: 'Sistemas Complexos & Vida',
        tags: ['Autômato Celular', 'SOC', 'Física Granular'],
        accentText: 'text-amber-300',
        accentBorder: 'hover:border-amber-400/50',
        accentBg: 'bg-amber-500/10',
        iconName: 'Hourglass',
    },
    {
        slug: 'physarum',
        title: 'Physarum Transport Network',
        shortTitle: 'Physarum Network',
        description: 'Bio-mimetismo de fungos amebóides inteligentes: agentes quimiotáticos gerando redes biológicas de transporte e auto-organização.',
        action: 'Alimentar Fungo',
        category: 'complex',
        categoryLabel: 'Sistemas Complexos & Vida',
        tags: ['Agentes Quimiotáticos', 'Bio-Mimetismo', 'Redes Tubulares'],
        accentText: 'text-lime-400',
        accentBorder: 'hover:border-lime-500/50',
        accentBg: 'bg-lime-500/10',
        iconName: 'Network',
    },
    {
        slug: 'ferrofluid',
        title: 'Ferrofluid Spikes & Magnetic Fields',
        shortTitle: 'Ferrofluid Spikes',
        description: 'Instabilidade magnética de Rosensweig em tempo real com espinhos cônicos afiados, reflexão metálica e pólos magnéticos dinâmicos.',
        action: 'Ativar Campo Magnético',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['Canvas 2D', 'Instabilidade Rosensweig', 'Magnetismo'],
        accentText: 'text-cyan-400',
        accentBorder: 'hover:border-cyan-500/50',
        accentBg: 'bg-cyan-500/10',
        iconName: 'Magnet',
    },
    {
        slug: 'ink',
        title: 'Ink in Water & Vortex Plumes',
        shortTitle: 'Ink in Water',
        description: 'Advecção viscosa de pigmentos na água com instabilidades de Rayleigh-Taylor, vórtices de Kelvin-Helmholtz e mistura cromática.',
        action: 'Injetar Pigmento',
        category: 'complex',
        categoryLabel: 'Sistemas Complexos & Vida',
        tags: ['Canvas 2D', 'Rayleigh-Taylor', 'Vórtices Hidrodinâmicos'],
        accentText: 'text-pink-400',
        accentBorder: 'hover:border-pink-500/50',
        accentBg: 'bg-pink-500/10',
        iconName: 'Pipette',
    },
    {
        slug: 'attractor',
        title: 'Strange Attractors & Manifolds',
        shortTitle: 'Strange Attractors',
        description: 'Atratores estranhos tridimensionais (Lorenz, Aizawa, Rössler, Thomas, Halvorsen) com integração RK4 e órbita 3D interativa.',
        action: 'Navegar no Hiperespaço',
        category: 'optics',
        categoryLabel: 'Óptica, Ondas & Caos',
        tags: ['Canvas 2D', 'Física RK4', 'Manifolds 3D', 'Caos Determinístico'],
        accentText: 'text-violet-400',
        accentBorder: 'hover:border-violet-500/50',
        accentBg: 'bg-violet-500/10',
        iconName: 'Orbit',
    },
    {
        slug: 'ripples',
        title: 'Wave Ripple Tank & Optical Caustics',
        shortTitle: 'Ripple Tank',
        description: 'Equação de onda 2D em tempo real com difração de fenda dupla, cáusticas ópticas subaquáticas e efeito Doppler.',
        action: 'Perturbar Superfície',
        category: 'optics',
        categoryLabel: 'Óptica, Ondas & Caos',
        tags: ['Canvas 2D', 'Equação de Onda 2D', 'Cáusticas Ópticas', 'Efeito Doppler'],
        accentText: 'text-sky-400',
        accentBorder: 'hover:border-sky-500/50',
        accentBg: 'bg-sky-500/10',
        iconName: 'Waves',
    },
    {
        slug: 'galaxy',
        title: 'N-Body Galactic Collision & Dark Matter',
        shortTitle: 'Galactic Collision',
        description: 'Simulação gravitacional N-corpos com integração simplética leapfrog, caudas de maré intergalácticas e halo de matéria escura.',
        action: 'Colidir Galáxias',
        category: 'physics',
        categoryLabel: 'Física & Gravidade',
        tags: ['Canvas 2D', 'Leapfrog Simplético', 'Gravitação N-Corpos', 'Matéria Escura'],
        accentText: 'text-blue-400',
        accentBorder: 'hover:border-blue-500/50',
        accentBg: 'bg-blue-500/10',
        iconName: 'Telescope',
    },
];

export const EXPERIMENT_MAP: Record<string, LabItem> = Object.fromEntries(
    LAB_ITEMS.map((item) => [item.slug, item])
);

export const EXPERIMENT_NAMES: Record<string, string> = Object.fromEntries(
    LAB_ITEMS.map((item) => [item.slug, item.shortTitle])
);
